### ISSUE TITLE
Mirror this FAQ to Gh-pages branch ?

### ISSUE THREAD

**Issue by Yonaba** [stevedonovan/luafaq#1]
Just an idea I am throwing upon the table, why not pushing this repository contents in a gh-pages branch ? So that one can easily reach  this FAQ contents from the address http://stevedonovan.io/luafaq ?

**Comment by stevedonovan** [comment]
It's meant to be hosted separately on http://luafaq.org (kindly organized by Patrick Donnelly); up to now we've been using a private subversion repo.  The idea is to open up the process so it's easier for user contributions!

(I suppose we could redirect luafaq.org to gh-pages, but existing system works...)

**Comment by Yonaba** [comment]
Alright. I'd rather vote for the redirection, too.
Anyway, I can close this.
Thanks for the reply.
